# ============================================================================
# DEVELOPMENT ENVIRONMENT CONFIGURATION
# ============================================================================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3307/youth_connect_db?useSSL=false&serverTimezone=Africa/Nairobi
    username: root
    password: Douglas20!
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # Auto-update schema in dev

# Development-specific settings
app:
  environment: development
  upload:
    upload-dir: ./uploads  # Local directory in project
    virus-scan-enabled: false
  cache:
    ttl: 60  # Short TTL for dev (1 minute)

# Verbose logging for development
logging:
  level:
    root: DEBUG
    com.youthconnect.user_service: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Eureka disabled in dev
eureka:
  client:
    enabled: false