apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: youthconnect
  labels:
    app: service-registry
    component: discovery
    version: "2.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
        component: discovery
        version: "2.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8761"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      serviceAccountName: service-registry
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - service-registry
                topologyKey: kubernetes.io/hostname
      containers:
        - name: service-registry
          image: youthconnect/service-registry:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8761
              protocol: TCP
          envFrom:
            - configMapRef:
                name: service-registry-config
          env:
            - name: EUREKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-registry-secret
                  key: eureka-username
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-registry-secret
                  key: eureka-password
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          volumeMounts:
            - name: logs
              mountPath: /var/log/youth-connect
      volumes:
        - name: logs
          emptyDir: {}
      terminationGracePeriodSeconds: 30