# ================================================================================
# Kubernetes Secret for Service Registry
# ================================================================================
# IMPORTANT: This is a TEMPLATE. Never commit actual secrets to version control!
#
# To create the secret in Kubernetes:
# kubectl create secret generic service-registry-secret \
#   --from-literal=eureka-username=admin \
#   --from-literal=eureka-password=your-secure-password \
#   -n youthconnect
# ================================================================================

apiVersion: v1
kind: Secret
metadata:
  name: service-registry-secret
  namespace: youthconnect
  labels:
    app: service-registry
    component: discovery
type: Opaque
data:
  # Base64-encoded credentials (CHANGE IN PRODUCTION!)
  # To encode: echo -n 'admin' | base64
  eureka-username: YWRtaW4=
  # To encode: echo -n 'changeme_in_production' | base64
  eureka-password: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-registry
  namespace: youthconnect
  labels:
    app: service-registry
    component: discovery