apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: youthconnect
  labels:
    app: service-registry
    component: discovery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8761"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: service-registry