# =================================================================================
# Youth Connect Uganda - Auth Service Test Configuration
# =================================================================================

spring:
  application:
    name: auth-service-test

  # Test Database (H2 In-Memory)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  # Test Redis (Embedded)
  data:
    redis:
      host: localhost
      port: 6370 # Different port for testing

  # Flyway disabled for tests (use create-drop)
  flyway:
    enabled: false

# JWT Configuration (Test)
jwt:
  secret: testSecretKeyForJWTTokenGenerationMinimum256BitsRequired
  expiration: 3600000       # 1 hour
  refresh-expiration: 604800000 # 7 days
  issuer: youth-connect-auth-service-test
  audience: youth-connect-platform-test

# Eureka disabled for tests
eureka:
  client:
    enabled: false

# Disable circuit breakers in tests
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: false
  retry:
    configs:
      default:
        maxAttempts: 1

# Logging for tests
logging:
  level:
    root: INFO
    com.youthconnect.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# Test-specific settings
app:
  security:
    password:
      min-length: 8
      max-attempts: 5
      lockout-duration-minutes: 30
  password-reset:
    token-expiry-minutes: 15
    max-attempts: 3