# ========================================
# CONTENT SERVICE - COMPLETE CONFIGURATION
# ========================================

# ========================================
# SERVER CONFIGURATION
# ========================================
server:
  port: 8084
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# ========================================
# SPRING APPLICATION
# ========================================
spring:
  application:
    name: content-service

  # ========================================
  # DATABASE CONFIGURATION (MySQL)
  # ========================================
  datasource:
    url: jdbc:mysql://localhost:3307/epb_db?useSSL=false&serverTimezone=Africa/Nairobi&allowPublicKeyRetrieval=true
    username: root
    password: Douglas20!
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP Connection Pool (Production-grade performance)
    hikari:
      pool-name: ContentServicePool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1

  # ========================================
  # JPA / HIBERNATE CONFIGURATION
  # ========================================
  jpa:
    hibernate:
      ddl-auto: update  # Change to 'validate' in production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    show-sql: false  # Set to true for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true

    open-in-view: false  # Prevent lazy loading issues

  # ========================================
  # CACHE CONFIGURATION
  # ========================================
  cache:
    type: caffeine
    cache-names:
      - learningModules
      - moduleProgress
      - posts
      - comments
      - postVotes
      - commentVotes
      - userPreferences
      - moderationQueue
      - trendingPosts

    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s

# ========================================
# EUREKA CLIENT CONFIGURATION
# ========================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true

  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      version: 1.0.0
      description: "Content Management Service - Learning Modules & Community"

# ========================================
# FEIGN CLIENT CONFIGURATION
# ========================================
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: BASIC

  circuitbreaker:
    enabled: true

# ========================================
# RESILIENCE4J (Circuit Breaker)
# ========================================
resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      notificationService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      fileService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

# ========================================
# ACTUATOR (Health Checks & Metrics)
# ========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10GB

  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:dev}

# ========================================
# LOGGING CONFIGURATION
# ========================================
logging:
  level:
    root: INFO
    com.youthconnect.content_service: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/content-service.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

# ========================================
# SPRINGDOC (OpenAPI/Swagger)
# ========================================
springdoc:
  api-docs:
    path: /api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

  show-actuator: true

# ========================================
# APPLICATION-SPECIFIC PROPERTIES
# ========================================
app:
  content:
    # Module configuration
    module:
      max-duration-minutes: 120
      supported-languages: en,lg,lur,lgb
      default-language: en
      audio-formats: mp3,m4a,wav
      max-audio-size-mb: 50

    # Community configuration
    community:
      max-post-length: 5000
      max-comment-length: 2000
      max-title-length: 255
      max-thread-depth: 5
      posts-per-page: 20
      auto-moderation-enabled: true

    # Moderation settings
    moderation:
      prohibited-words:
        - spam
        - scam
        - fraud
      max-urls-per-post: 2
      caps-threshold: 0.5
      phone-number-regex: "\\+?256\\d{9}"

  # Service URLs (for Feign clients)
  services:
    user-service:
      name: user-service
      url: http://user-service

    notification-service:
      name: notification-service
      url: http://notification-service

    file-service:
      name: file-management-service
      url: http://file-management-service

    analytics-service:
      name: analytics-service
      url: http://analytics-service

# ========================================
# PROFILE-SPECIFIC CONFIGURATIONS
# ========================================
---
# DEVELOPMENT PROFILE
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.youthconnect.content_service: DEBUG
    org.hibernate.SQL: DEBUG

---
# PRODUCTION PROFILE
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-update schema in production
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.youthconnect.content_service: INFO
    org.hibernate.SQL: WARN

server:
  compression:
    enabled: true

management:
  endpoint:
    health:
      show-details: when-authorized

---
# TEST PROFILE
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false