# =================================================================================
# Prometheus Configuration for Entrepreneurship Booster Platform
# Purpose: Metrics collection, alerting rules, and service discovery
# =================================================================================

global:
  scrape_interval: 15s          # Scrape metrics every 15 seconds
  evaluation_interval: 15s      # Evaluate rules every 15 seconds
  scrape_timeout: 10s           # Timeout for scrape requests

  # External labels for federated setups or Alertmanager
  external_labels:
    cluster: 'epb-production'
    environment: 'production'
    region: 'uganda-kampala'

# Alertmanager configuration (optional, for production alerts)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
      timeout: 10s

# Load alerting rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# =================================================================================
# SCRAPE CONFIGURATIONS
# =================================================================================

scrape_configs:
  # -------------------------------------------------------------------------------
  # Prometheus Self-Monitoring
  # -------------------------------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          tier: 'monitoring'

  # -------------------------------------------------------------------------------
  # Service Registry (Eureka Server)
  # -------------------------------------------------------------------------------
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['service-registry:8761']
        labels:
          service: 'eureka-server'
          tier: 'infrastructure'

  # -------------------------------------------------------------------------------
  # API Gateway
  # -------------------------------------------------------------------------------
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s  # More frequent for gateway
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'
          tier: 'infrastructure'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # User Service
  # -------------------------------------------------------------------------------
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: 'user-service'
          tier: 'core'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Authentication Service
  # -------------------------------------------------------------------------------
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['auth-service:8082']
        labels:
          service: 'auth-service'
          tier: 'core'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Opportunity Service
  # -------------------------------------------------------------------------------
  - job_name: 'opportunity-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['opportunity-service:8083']
        labels:
          service: 'opportunity-service'
          tier: 'business'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Content Service
  # -------------------------------------------------------------------------------
  - job_name: 'content-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['content-service:8084']
        labels:
          service: 'content-service'
          tier: 'business'

  # -------------------------------------------------------------------------------
  # Mentor Service
  # -------------------------------------------------------------------------------
  - job_name: 'mentor-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['mentor-service:8085']
        labels:
          service: 'mentor-service'
          tier: 'business'

  # -------------------------------------------------------------------------------
  # Notification Service
  # -------------------------------------------------------------------------------
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['notification-service:8086']
        labels:
          service: 'notification-service'
          tier: 'integration'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # USSD Service
  # -------------------------------------------------------------------------------
  - job_name: 'ussd-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s  # More frequent for real-time USSD
    static_configs:
      - targets: ['ussd-service:8087']
        labels:
          service: 'ussd-service'
          tier: 'integration'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # File Management Service
  # -------------------------------------------------------------------------------
  - job_name: 'file-management-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['file-management-service:8088']
        labels:
          service: 'file-management'
          tier: 'storage'

  # -------------------------------------------------------------------------------
  # AI Recommendation Service
  # -------------------------------------------------------------------------------
  - job_name: 'ai-recommendation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['ai-recommendation-service:8089']
        labels:
          service: 'ai-recommendation'
          tier: 'ml'

  # -------------------------------------------------------------------------------
  # Analytics Service
  # -------------------------------------------------------------------------------
  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['analytics-service:8090']
        labels:
          service: 'analytics'
          tier: 'analytics'

  # -------------------------------------------------------------------------------
  # Edge Functions Service
  # -------------------------------------------------------------------------------
  - job_name: 'edge-functions'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['edge-functions:8091']
        labels:
          service: 'edge-functions'
          tier: 'orchestration'

  # -------------------------------------------------------------------------------
  # MySQL Database Exporter
  # -------------------------------------------------------------------------------
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          service: 'mysql'
          tier: 'database'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Redis Exporter
  # -------------------------------------------------------------------------------
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          tier: 'cache'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Nginx Exporter
  # -------------------------------------------------------------------------------
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          tier: 'infrastructure'
          critical: 'true'

  # -------------------------------------------------------------------------------
  # Node Exporter (System Metrics)
  # -------------------------------------------------------------------------------
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          tier: 'infrastructure'

  # -------------------------------------------------------------------------------
  # cAdvisor (Container Metrics)
  # -------------------------------------------------------------------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          tier: 'monitoring'

# =================================================================================
# RELABEL CONFIGURATIONS (Advanced)
# =================================================================================
# Uncomment for dynamic service discovery via Consul/Kubernetes

# - job_name: 'spring-actuator'
#   consul_sd_configs:
#     - server: 'consul:8500'
#   relabel_configs:
#     - source_labels: [__meta_consul_tags]
#       regex: .*,spring-actuator,.*
#       action: keep
#     - source_labels: [__meta_consul_service]
#       target_label: service
#     - source_labels: [__address__]
#       target_label: __address__
#       replacement: '$1:$2'