// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtbmoxcxrbluhkakvzdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Ym1veGN4cmJsdWhrYWt2emRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDM0ODQsImV4cCI6MjA3MTg3OTQ4NH0.IIqWwu8HQUbYa3LnelXXZzrfInQ4SwG61hsmdcal_wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});