# ==============================================================================
# Edge Functions Service - Spring Boot Configuration
# Version: 1.0.0
# ==============================================================================

server:
  port: ${SERVER_PORT:8085}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true

spring:
  application:
    name: edge-functions-service
  
  # ===========================================================================
  # CLOUD CONFIGURATION
  # ===========================================================================
  cloud:
    config:
      enabled: false
    
    # OpenFeign Configuration
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: BASIC
      
      # Compression
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true
      
      # Circuit Breaker
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

# ==============================================================================
# EUREKA SERVICE DISCOVERY
# ==============================================================================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:edge-functions}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    
    # Health Check
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    
    # Metadata
    metadata-map:
      version: 1.0.0
      description: "Edge Functions Service - USSD, AI, Multi-Service Orchestration"
      management.context-path: /actuator

# ==============================================================================
# OPENAI API CONFIGURATION
# ==============================================================================
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-key-here}
    base-url: ${OPENAI_API_BASE_URL:https://api.openai.com/v1}
    default-chat-model: ${OPENAI_API_DEFAULT_CHAT_MODEL:gpt-4o-mini}
    default-tts-model: ${OPENAI_API_DEFAULT_TTS_MODEL:tts-1}
    default-voice: ${OPENAI_API_DEFAULT_VOICE:alloy}
    whisper-model: ${OPENAI_API_WHISPER_MODEL:whisper-1}
    request-timeout-ms: ${OPENAI_API_REQUEST_TIMEOUT:30000}
    max-tokens: ${OPENAI_API_MAX_TOKENS:200}
    temperature: ${OPENAI_API_TEMPERATURE:0.7}
    enabled: ${OPENAI_API_ENABLED:true}

# ==============================================================================
# RESILIENCE4J CONFIGURATION
# ==============================================================================
resilience4j:
  # Circuit Breaker
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.Exception
        ignore-exceptions:
          - java.lang.IllegalArgumentException
    
    instances:
      multiService:
        base-config: default
      orchestration:
        base-config: default
        failure-rate-threshold: 60
      openai:
        base-config: default
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 70
      ussd:
        base-config: default
        sliding-window-size: 20
  
  # Retry
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - java.lang.SecurityException
    
    instances:
      multiService:
        base-config: default
      orchestration:
        base-config: default
      openai:
        base-config: default
        max-attempts: 2
      ussd:
        base-config: default
        max-attempts: 2
  
  # Rate Limiter
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 5s
    
    instances:
      default:
        base-config: default
      openai:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 10s
      ussd:
        limit-for-period: 1000
        limit-refresh-period: 1m
        timeout-duration: 1s
  
  # Time Limiter
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: true
    
    instances:
      default:
        base-config: default
      openai:
        timeout-duration: 30s
      ussd:
        timeout-duration: 3s

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.youthconnect.edge_functions: ${LOGGING_LEVEL_COM_YOUTHCONNECT:DEBUG}
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    io.github.resilience4j: DEBUG
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: ${LOGGING_FILE_NAME:logs/edge-functions.log}
    max-size: 10MB
    max-history: 30

# ==============================================================================
# ACTUATOR (MONITORING & HEALTH)
# ==============================================================================
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
      base-path: /actuator
  
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:when-authorized}
      probes:
        enabled: true
    
    metrics:
      enabled: true
    
    prometheus:
      enabled: true
  
  metrics:
    export:
      prometheus:
        enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}
    
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# ==============================================================================
# APPLICATION INFO
# ==============================================================================
info:
  app:
    name: ${spring.application.name}
    description: "Edge Functions Service - USSD, AI, Multi-Service Orchestration"
    version: 1.0.0
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
  
  team:
    developer: "Douglas Kings Kato"
    organization: "Youth Entrepreneurship Booster Platform"
    sponsor: "Woord en Daad / EU-YEPPAD"

# ==============================================================================
# FEATURE FLAGS
# ==============================================================================
features:
  ai:
    enabled: ${FEATURE_AI_ENABLED:true}
  ussd:
    enabled: ${FEATURE_USSD_ENABLED:true}
  sms:
    enabled: ${FEATURE_SMS_ENABLED:true}
  email:
    enabled: ${FEATURE_EMAIL_ENABLED:true}
  push-notifications:
    enabled: ${FEATURE_PUSH_NOTIFICATIONS_ENABLED:false}

# ==============================================================================
# PROFILE-SPECIFIC CONFIGURATION
# ==============================================================================
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG
    com.youthconnect.edge_functions: TRACE

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.youthconnect.edge_functions: INFO

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30