# =============================================================================
# MENTOR SERVICE - PRODUCTION CONFIGURATION
# =============================================================================

spring:
  application:
    name: mentor-service

  profiles:
    active: prod

  # Database Configuration (Production)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      pool-name: MentorServiceHikariPool-Prod

  # JPA Configuration (Production)
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    hibernate:
      ddl-auto: validate

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # Cache Configuration
  cache:
    type: caffeine
    cache-names:
      - mentors
      - sessions
      - availability
      - reviews
      - statistics
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=60m

# Server Configuration
server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  connection-timeout: 30000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
    registry-fetch-interval-seconds: 30

  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      version: ${project.version:1.0.0}
      environment: prod

# Feign Client
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: BASIC
      user-service:
        url: ${USER_SERVICE_URL:http://user-service}
      notification-service:
        url: ${NOTIFICATION_SERVICE_URL:http://notification-service}
  circuitbreaker:
    enabled: true

# Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      notification-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      diskspace:
        enabled: true
        threshold: 10MB
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      jvm: true
      process: true
      system: true
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: simple

# Logging (Production)
logging:
  level:
    root: WARN
    com.youthconnect.mentor_service: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    feign: INFO
    com.zaxxer.hikari: INFO
  file:
    name: ${LOG_FILE:/var/log/mentor-service/application.log}
    max-size: 50MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Springdoc OpenAPI
springdoc:
  api-docs:
    enabled: false  # Disabled in production for security
  swagger-ui:
    enabled: false  # Disabled in production for security

# Custom Application Properties
app:
  mentorship:
    default-session-duration: 60
    max-sessions-per-week: 10
    min-session-gap: 30
    reminder-times:
      - 24
      - 1
    auto-cancel-threshold: 24

  reviews:
    min-rating: 1
    max-rating: 5
    moderation-enabled: true
    min-comment-length: 10
    max-comment-length: 500

  matching:
    min-match-score: 60
    weights:
      expertise: 0.4
      rating: 0.3
      availability: 0.2
      location: 0.1

  cache:
    ttl:
      mentors: 3600
      sessions: 600
      availability: 900
      reviews: 7200
      statistics: 3600

  features:
    video-calls-enabled: ${VIDEO_CALLS_ENABLED:true}
    calendar-integration-enabled: ${CALENDAR_INTEGRATION_ENABLED:true}
    ai-matching-enabled: ${AI_MATCHING_ENABLED:true}
    auto-reminders-enabled: ${AUTO_REMINDERS_ENABLED:true}