# Service Configuration
spring:
  application:
    name: opportunity-service
  datasource:
    url: jdbc:mysql://localhost:3307/youth_connect_db
    username: root
    password: Douglas20!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

server:
  port: 8082

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# Actuator Configuration for Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom Application Properties
youthconnect:
  opportunity:
    serviceName: opportunity-service
    version: 1.0.0

    opportunity:
      reminderDaysBeforeDeadline: 7
      maxOpportunitiesPerMonth: 50
      autoCloseDaysAfterDeadline: 3
      enableAiMatching: true
      minMatchingScore: 0.6

    application:
      maxApplicationsPerDay: 20
      autoReviewAfterDays: 14
      enableDuplicateDetection: true
      maxAttachmentsPerApplication: 5

    integration:
      userServiceUrl: http://user-service
      notificationServiceUrl: http://notification-service
      analyticsServiceUrl: http://analytics-service
      serviceCallTimeout: 5000
      retryAttempts: 3

    fileUpload:
      maxFileSize: 10485760
      allowedExtensions: pdf,doc,docx,jpg,jpeg,png
      uploadPath: ./uploads/applications

    cache:
      opportunityListTtl: 300
      opportunityDetailTtl: 600
      maxCacheSize: 1000

# Logging Configuration
logging:
  level:
    root: INFO
    com.youthconnect.opportunity_service: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
