# ============================================================
# Production Environment Configuration
# ============================================================

# Production Profile
spring:
  profiles:
    active: prod

  jpa:
    show-sql: false

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/youth_connect_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

# Server and Security Settings
server:
  error:
    include-message: never
    include-stacktrace: never

# Logging Configuration for Production
logging:
  level:
    root: WARN
    com.youthconnect.opportunity_service: INFO

# Production Cache Settings
youthconnect:
  opportunity:
    cache:
      opportunityListTtl: 600
      opportunityDetailTtl: 1200
